### ISSUE TITLE
exception in /karma

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#132]
```
Oops in each review of yours, which was up-voted: {:"2020-04-22"=>1}, 2020-02-05 20:01:33 +0000
	/app/objects/karma.rb:236:in `pts'
	/app/objects/karma.rb:223:in `block (2 levels) in recent'
	/app/objects/karma.rb:219:in `map'
	/app/objects/karma.rb:219:in `block in recent'
	/app/objects/karma.rb:217:in `map'
	/app/objects/karma.rb:217:in `recent'
	/app/vendor/bundle/ruby/2.6.0/gems/tacky-0.3.5/lib/tacky.rb:56:in `block in method_missing'
	/app/vendor/bundle/ruby/2.6.0/gems/tacky-0.3.5/lib/tacky.rb:54:in `synchronize'
	/app/vendor/bundle/ruby/2.6.0/gems/tacky-0.3.5/lib/tacky.rb:54:in `method_missing'
	/app/front/front_karma.rb:26:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.50`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#132` is not assigned, can't get performer
