### ISSUE TITLE
undefined method `start_with?' for nil:NilClass

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#150]
```
undefined method `start_with?' for nil:NilClass
	/app/objects/bots.rb:43:in `is?'
	(haml):6:in `block in render'
	/app/vendor/bundle/ruby/2.6.0/gems/haml-5.0.4/lib/haml/engine.rb:126:in `eval'
	/app/vendor/bundle/ruby/2.6.0/gems/haml-5.0.4/lib/haml/engine.rb:126:in `render'
	/app/front/front_helpers.rb:26:in `partial'
	/app/views/project.haml:57:in `block in __tilt_47070858686360'
	/app/views/project.haml:51:in `each'
	/app/views/project.haml:51:in `__tilt_47070858686360'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.60`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#150` is not assigned, can't get performer
