### ISSUE TITLE
insert or update on table "seen" violates foreign key constraint "seen_project_fkey"

### ISSUE THREAD

**Issue by yegor256** [yegor256/codexia#153]
```
PG::ForeignKeyViolation: ERROR:  insert or update on table "seen" violates foreign key constraint "seen_project_fkey"
DETAIL:  Key (project)=(0) is not present in table "project".

  from pgtk/pool.rb:142:in `exec_params'
  from pgtk/pool.rb:142:in `exec'
  from pgtk/pool.rb:112:in `block in exec'
  from pgtk/pool.rb:166:in `connect'
  from pgtk/pool.rb:105:in `exec'
  from objects/project.rb:122:in `seen!'
  from objects/sieve.rb:47:in `method_missing'
  from front/front_project.rb:46:in `block in <top (required)>'
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.62`

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#153` is not assigned, can't get performer
