### ISSUE TITLE
`Duplicate key` internal error during review creation

### ISSUE THREAD

**Issue by iakunin** [yegor256/codexia#94]
## Steps to reproduce
1. Create review to projectId=11 with hash=f678742d-991d-439f-8940-8c32ff5e4373

```
curl --location --request POST 'https://www.codexia.org/p/11/post?text=Seems%20that%20this%20repository%20is%20a%20fake%20one%20and%20it%20was%20only%20for%20testing%20purposes%20so%20it%20should%20be%20definitely%20deleted%20with%20hash.hhhh..&hash=f678742d-991d-439f-8940-8c32ff5e4373' \
--header 'X-Codexia-Token: <token>'
```

## Expected behavior

Either 200 http response code with appropriate message in html-body (review cannot be created because review with this hash already exists).

Or some special http response code indicating that review wasn't created besause review with this hash already exists.

That's required for retry attempts during review creation via api. It's necessary to discern internal errors that require retry from ones that doesn't require retry.

## Actual behavior

An internal error with 503 http response code:

```
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Content-Length: 5562
Content-Type: text/html;charset=utf-8
Date: Mon, 16 Mar 2020 11:26:49 GMT
Server: nginx
Set-Cookie: flash_color=; domain=www.codexia.org; path=/; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 -0000; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html>
<head>
<title>Ouch... :(</title>
<meta charset='UTF-8'>
<link href='https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css.min.css' rel='stylesheet'>
<link href='https://www.codexia.org/logo-64.png' rel='shortcut icon'>
</head>
<body>
<p style='color: red;'>
Internal error at
0.0.33
</p>
<p>
Please help us improve our service and submit the following
stacktrace to our issue tracker in GitHub:
<a href='https://github.com/yegor256/codexia'>yegor256/codexia</a>
</p>
<pre>ERROR:  duplicate key value violates unique constraint &quot;unique_hash&quot;
DETAIL:  Key (project, hash)=(11, f678742d-991d-439f-8940-8c32ff5e4373) already exists.

	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.7.5/lib/pgtk/pool.rb:142:in `exec_params&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.7.5/lib/pgtk/pool.rb:142:in `exec&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.7.5/lib/pgtk/pool.rb:112:in `block in exec&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.7.5/lib/pgtk/pool.rb:166:in `connect&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/pgtk-0.7.5/lib/pgtk/pool.rb:105:in `exec&#39;
	/app/objects/reviews.rb:50:in `post&#39;
	/app/front/front_project.rb:83:in `block in &lt;top (required)&gt;&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1635:in `block in compile!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (3 levels) in route!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1011:in `route_eval&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:992:in `block (2 levels) in route!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1040:in `block in process_route&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `catch&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1038:in `process_route&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:990:in `block in route!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `each&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:989:in `route!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1097:in `block in dispatch!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1094:in `dispatch!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `block in call!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `block in invoke&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `catch&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1076:in `invoke&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:924:in `call!&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:913:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-ssl-1.4.1/lib/rack/ssl.rb:27:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/xss_header.rb:18:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/path_traversal.rb:16:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/json_csrf.rb:26:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/base.rb:50:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-protection-2.0.4/lib/rack/protection/frame_options.rb:31:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/logger.rb:15:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/common_logger.rb:33:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:231:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:224:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/head.rb:12:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/rack-2.0.6/lib/rack/method_override.rb:22:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:194:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1957:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `block in call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1729:in `synchronize&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/sinatra-2.0.4/lib/sinatra/base.rb:1502:in `call&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/thin-1.7.2/lib/thin/connection.rb:50:in `block in process&#39;
	/app/vendor/bundle/ruby/2.6.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:1077:in `block in spawn_threadpool&#39;</pre>
</body>
</html>
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.0.34`

**Comment by yegor256** [comment]
@iakunin should be OK now, pay attention to the `Location` header of the response

**Comment by iakunin** [comment]
@yegor256 unfortunately, I cannot see the `Location` header in the response:


Request:
```
curl --location --request POST 'https://www.codexia.org/p/11/post?text=Seems%20that%20this%20repository%20is%20a%20fake%20one%20and%20it%20was%20only%20for%20testing%20purposes%20so%20it%20should%20be%20definitely%20deleted%20with%20hash.hhhh..&hash=f678742d-991d-439f-8940-8c32ff5e4373' \
--header 'X-Codexia-Token: <token>'
```

Response:
```
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html;charset=utf-8
Date: Mon, 16 Mar 2020 16:31:34 GMT
Server: nginx
Set-Cookie: flash_msg=; domain=www.codexia.org; path=/; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 -0000; secure; HttpOnly
Set-Cookie: flash_color=; domain=www.codexia.org; path=/; max-age=0; expires=Thu, 01 Jan 1970 00:00:00 -0000; secure; HttpOnly
Strict-Transport-Security: max-age=31536000
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Cascade: pass
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<!DOCTYPE html>
<html>
<head>
<title>https://www.codexia.org/duplicate</title>
<meta charset='UTF-8'>
<meta content='width=device-width, initial-scale=1.0' name='viewport'>
<meta content='investment, open source, incubator' name='keywords'>
<meta content='Open Source Incubator' name='description'>
<link href='https://cdn.jsdelivr.net/gh/yegor256/tacit@gh-pages/tacit-css.min.css' rel='stylesheet'>
<link href='https://cdn.jsdelivr.net/gh/yegor256/drops@gh-pages/drops.min.css' rel='stylesheet'>
<link href='https://www.yegor256.com/css/icons.css' rel='stylesheet'>
<link href='https://www.codexia.org/logo-64.png' rel='shortcut icon'>
<script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>
<style>
  body { padding: 1em; }
  section { width: 700px; }
  article { border: 0 }
  header, article, footer { padding: 1em; }
  nav ul { margin-bottom: 0.1em; }
  .item { margin-right: 1em; }
  .logo { width: 32px; height: 32px; vertical-align: middle; }
</style>
</head>
<body>
<section>
<header>
<nav>
<ul>
<li>
<a href='https://www.codexia.org/'>
<img alt='Logo' class='logo' src='https://www.codexia.org/logo.svg'>
</a>
</li>
</ul>
<ul>
<li>
<span title='Author ID: #7974'>
@iakunin-codexia-bot
<span title='You are a supervised bot'>⚙️</span>
</span>
</li>
<li title='Your karma'>
<a href='https://www.codexia.org/karma'>
+165
</a>
</li>
</ul>
<ul>
<li>
<li>
<a href='https://www.codexia.org/submit' title='Submit a new project'>
/submit
</a>
</li>
<li>
<a href='https://www.codexia.org/terms'>
/terms
</a>
</li>
<li>
<a href='https://www.codexia.org/api'>
/api
</a>
</li>
<li>
<a href='https://www.codexia.org/logout'>
/logout
</a>
</li>
</li>
</ul>
</nav>
</header>
<article>
<p style='background-color:darkgreen; color:white; border-radius:2px; padding:0.2em 0.4em;'>
Duplicate review: A review with this hash already exists
</p>
<p class='firebrick'>
This page is not here.
</p>
<p>
Most likely the link is broken or expired.
Try to start from
<a href='https://www.codexia.org/'>here</a>.
</p>

</article>
<footer class='smaller gray'>
<nav>
<ul>
<li>
&copy; 2020
<a href='/welcome'>Codexia</a>
</li>
<li class='monospace' title='Release version and currently deployed version'>
8d537e5/0.0.34
</li>
<li title='PostgreSQL version'>
pg:12.0
</li>
<li title='Your IP address visible to the server'>
<a href='https://iplocation.com/?ip=91.77.139.243'>
91.77.139.243
</a>
</li>
<li title='This request processing time'>
16ms
</li>
</ul>
</nav>
<nav>
<ul>
<li>
<a href='https://github.com/yegor256/codexia/stargazers'><img alt='GitHub' src='https://img.shields.io/github/stars/yegor256/codexia.svg?style=flat-square'></a>
</li>
<li>
<a href='https://www.sixnines.io/h/8754'><img alt='SixNines' src='https://www.sixnines.io/b/8754?style=flat'></a>
</li>
</ul>
</nav>
</footer>
</section>
</body>
</html>
```

**Comment by 0crat** [comment]
Job `gh:yegor256/codexia#94` is not assigned, can't get performer
